use std::path::Path;

use tokio::process::Command;

use crate::error::{AppError, AppResult};

const CONTAINER_NAME: &str = "sail-manager-dns";
const IMAGE: &str = "4km3/dnsmasq:latest";
pub const HOST_PORT: u16 = 5354;

pub async fn ensure_running(conf_dir: &Path, tld: &str) -> AppResult<()> {
    tokio::fs::create_dir_all(conf_dir).await?;
    let config_changed = write_config(conf_dir, tld).await?;

    let inspect = Command::new("docker")
        .args(["inspect", CONTAINER_NAME, "--format", "{{.State.Running}}"])
        .output()
        .await?;

    if inspect.status.success() {
        let running = String::from_utf8_lossy(&inspect.stdout).trim() == "true";
        if running {
            // Only restart to reload config when it actually changed. dnsmasq
            // doesn't auto-pick up mount changes, but restarting on every
            // project create/delete (when the TLD is unchanged) needlessly
            // drops `.<tld>` resolution mid-use.
            if config_changed {
                let _ = Command::new("docker")
                    .args(["restart", CONTAINER_NAME])
                    .output()
                    .await;
            }
            return Ok(());
        }
        let out = Command::new("docker")
            .args(["start", CONTAINER_NAME])
            .output()
            .await?;
        if !out.status.success() {
            return Err(AppError::Other(format!(
                "could not start dnsmasq: {}",
                String::from_utf8_lossy(&out.stderr).trim()
            )));
        }
        return Ok(());
    }

    let conf_path = conf_dir.join("dnsmasq.conf");
    let mount_arg = format!("{}:/etc/dnsmasq.conf:ro", conf_path.display());
    let port_udp = format!("127.0.0.1:{HOST_PORT}:53/udp");
    let port_tcp = format!("127.0.0.1:{HOST_PORT}:53/tcp");

    let out = Command::new("docker")
        .args([
            "run",
            "-d",
            "--name",
            CONTAINER_NAME,
            "--restart",
            "unless-stopped",
            "-p",
            &port_udp,
            "-p",
            &port_tcp,
            "-v",
            &mount_arg,
            IMAGE,
        ])
        .output()
        .await?;

    if !out.status.success() {
        let stderr = String::from_utf8_lossy(&out.stderr).trim().to_string();
        return Err(AppError::Other(format!(
            "could not start dnsmasq container: {stderr}"
        )));
    }
    Ok(())
}

pub async fn stop() -> AppResult<()> {
    let _ = Command::new("docker")
        .args(["stop", CONTAINER_NAME])
        .output()
        .await;
    let _ = Command::new("docker")
        .args(["rm", CONTAINER_NAME])
        .output()
        .await;
    Ok(())
}

/// Write the dnsmasq config, returning `true` if the file's content actually
/// changed. Callers use this to avoid restarting the container when nothing
/// changed — a needless restart briefly drops `.<tld>` resolution.
async fn write_config(conf_dir: &Path, tld: &str) -> AppResult<bool> {
    let conf_path = conf_dir.join("dnsmasq.conf");
    let content = format!(
        "# Auto-generated by Sail Manager.\n\
         no-resolv\n\
         no-poll\n\
         address=/.{tld}/127.0.0.1\n"
    );
    let unchanged = matches!(
        tokio::fs::read_to_string(&conf_path).await,
        Ok(existing) if existing == content
    );
    if unchanged {
        return Ok(false);
    }
    tokio::fs::write(&conf_path, content).await?;
    Ok(true)
}
